# Generated by Django 2.0.3 on 2018-09-15 17:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointfeature',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
