# Generated by Django 2.0.3 on 2018-09-15 18:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp_projects', '0002_auto_20180915_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackfeature',
            name='linestring',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
    ]
