# Generated by Django 2.0.3 on 2018-09-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_projects', '0004_auto_20180917_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackfeature',
            name='lengthm',
            field=models.FloatField(blank=True, null=True, verbose_name='Track length in metres'),
        ),
    ]
