# Generated by Django 2.0.8 on 2018-10-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp_projects', '0005_trackfeature_lengthm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenote',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gp_projects.Note'),
        ),
    ]
