# Generated by Django 2.0.3 on 2018-04-25 20:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20180420_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherfiles',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
