# Generated by Django 2.0.3 on 2018-05-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_otherfiles_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.FileField(upload_to='projects/'),
        ),
    ]
