# Generated by Django 2.0.3 on 2018-05-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20180514_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basemap',
            name='url',
            field=models.FileField(upload_to='basemaps/'),
        ),
        migrations.AlterField(
            model_name='otherfiles',
            name='url',
            field=models.FileField(upload_to='otherfiles/'),
        ),
        migrations.AlterField(
            model_name='spatialitedbs',
            name='url',
            field=models.FileField(upload_to='spatialitedbs/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.FileField(upload_to='tags/'),
        ),
    ]
