# Generated by Django 2.0.3 on 2018-05-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20180514_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='demo',
        ),
    ]
