# Generated by Django 2.0.8 on 2018-09-22 19:03

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_remove_profile_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='document',
            field=models.FileField(upload_to=profiles.models.userproject_directory_path),
        ),
    ]
