# Generated by Django 2.0.8 on 2018-10-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20180922_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemap',
            options={'ordering': ('path', '-modifieddate')},
        ),
        migrations.AlterModelOptions(
            name='otherfiles',
            options={'ordering': ('path', '-modifieddate')},
        ),
        migrations.AlterModelOptions(
            name='profileset',
            options={'ordering': ('owner',)},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('path', '-modifieddate')},
        ),
        migrations.AlterModelOptions(
            name='spatialitedbs',
            options={'ordering': ('path', '-modifieddate')},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('path', '-modifieddate')},
        ),
        migrations.AlterModelOptions(
            name='userproject',
            options={'ordering': ('owner', '-modifieddate')},
        ),
    ]
