# Generated by Django 2.0.8 on 2018-10-10 19:46

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20181004_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.FileField(upload_to=profiles.models.tag_directory_path),
        ),
    ]
